git:
  depth: 3
addons:
    apt:
        packages:
          - dos2unix
dist: bionic
env:
  global:
    - secure: j64L+YB6ZTOwP7joFBfSAMv6scssInUw91BgJqc/dRLU6nd4d2n8as4qYGbGPZ09nIYES+baD7W73WVr0Hljvnis2wKA36BcuzyLlcGugUtuDigVG/X5RDWs4EYh5URSOFO5j+I+2QKFWnYKydiQbnimBdTr3SEI9QBGFoywNVRUPaOquuyQwk3dYb7s4Fc8NHkNJF9xJ/dq+GrFIBmXHDuq7d+J2Ex2rZ5LADBiResASnMLSUNLtrtzOlMi5GE7cT6xKpnNigc2EpKmhQxrWG1/P9x+KgIQvMG+7fbYzmr076Hvl5DGvRW1JDW69fbXOTCZtXBjveDV79JFd9+KJnYbBaMD262ZJJ+zFwhUu+faKOZqejeO10VRJONda4q3RBfcFF21nZmFbuI3t/pJWJpXX8+r1/5/OkMhvuZf6HNIQhrk2kKEUx6yaPW5xjKQLCrFkEASgImRFDzKtr1XFmh3fJAGsU/WDbtgs8hZy8YiiHHtUYckTG8RjZTLulO8VM277L1tWubNKYDUEhfg+c5bovl/XomttnGuXm5Z0Cve9ZOBc6leOPwi4FP5WsAXpD9AxJDOE1215OxZRX0LxKOAHVfPLfjSLABPeCc6JnfoE1c5HWVQg7OAfMveleDdNaOemkDp3O5klOsOmD2w4E7CZUc2IBz2FbsZQ2ML61U=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: mitchellkrog@gmail.com
    - TRAVIS_REPO_SLUG: mitchellkrogza/Badd-Boyz-Hosts
    - GIT_BRANCH: master
    - TZ:       Africa/Johannesburg
    - PYFUNCEBLE_CONFIG_DIR: ${TRAVIS_BUILD_DIR}/dev-tools/
    - PYFUNCEBLE_AUTO_CONFIGURATION: PyFunceble

language: python

python:
  - "3.7"

matrix:
  fast_finish: true

install:
  #- export PATH="${HOME}/miniconda/bin:${PATH}"
  #- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  #- bash miniconda.sh -b -p ${HOME}/miniconda
  #- hash -r
  #- conda config --set always_yes yes --set changeps1 no
  #- conda update -q conda
  #- conda create -q -n test-environment python="3.7.4"
  #- rm miniconda.sh
  #- source activate test-environment
  #- python -VV
  - pip3 install --upgrade pip
  - pip3 install PyFunceble-dev --pre
  - pip3 install ultimate-hosts-blacklist-whitelist-dev

script:
  - bash dev-tools/PrepareData.sh
  - bash dev-tools/DataTesting.sh

notifications:
on_success: never
on_failure: always
